##### ===== STATUS BAR ===== #####
set -g status on
set -g status-justify right
set -g status-position top
set -g status-style bg=default

set -g status-left "#{?client_prefix,#[reverse] COMANDO #[noreverse],}"
set -g status-right " | Sessao [ #S ] %H:%M:%S %d/%m/%Y"

set -g window-status-format '#I'
set -g window-status-current-format '#I#{?window_zoomed_flag,  ,}'
set -g window-status-current-style bg=#2e388e

##### ===== DEFAULT CONFIG ===== #####
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:RGB"

set -g default-command "exec /bin/bash"
set -g renumber-windows on
set -g base-index 1
set -g pane-base-index 1
set -g history-limit 500000
set -g mouse on

##### ===== PERFORMANCE / NVIM ===== #####
set -sg escape-time 10
set -g focus-events on
set -g xterm-keys on
# set -g extended-keys on
# set -g extended-keys-format csi-u
set -g allow-passthrough on
set -g visual-activity off

##### ===== PANES / UI ===== #####
set -g pane-border-format "#[fg=#000000 bg=colour46] #{pane_index} #{@custom_pane_title} "
# Versão compatível com tmux < 3.0
set-hook -g pane-focus-in 'if-shell "[ #{window_panes} -gt 1 ]" "set -g pane-border-status top" "set -g pane-border-status off"'

##### ===== MATRIX GREEN THEME ===== #####

set -g status-style bg=default,fg=colour46
set -g window-status-style fg=colour46
set -g window-status-current-style fg=colour46,bold

set -g pane-border-style fg=colour46
set -g pane-active-border-style fg=colour46,bold

##### ===== KEYBINDS ===== #####

# Criar janela (limitado a 3)
bind c if-shell '[ "#{session_windows}" -lt 3 ]' \
  'new-window' \
  'display-message "!! too many windows"'

# Toggle status bar
bind b run-shell "tmux setw -g status \$(tmux show -gv status | grep -q off && echo on || echo off)"

# Salvar histórico
bind a command-prompt -p "Salvar historico" -I "/tmp/__tmuxHistory_%H_%M_%S" \
  'capture-pane -JS - \; save-buffer %1 \; delete-buffer'

# Splits
bind \\ split-window -h -c '#{pane_current_path}'
bind -  split-window -v -c '#{pane_current_path}'

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Reload"

# Navegação estilo vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Rotacionar panes
bind p rotate-window

##### ===== SESSÕES ===== #####
bind Tab choose-tree -sZ
bind n command-prompt -p "Nome da nova Sessão:" "new-session -s '%%'"
bind $ command-prompt -I "#S" "rename-session '%%'"
bind g switch-client -n

##### ===== COPY MODE (VIM) ===== #####
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle \; send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
